b=int(input('enter the base of triangle'))
h=int(input('Enter the height of triangle'))
print('area of triangle is ',0.5*b*h)
s=int(input('Enter the side of a square'))
print('area of square is ',s*s)
l=int(input('enter the length of rect'))
w=int(input('enter the width of rect'))
print('area of rect is ',l*w)